### ISSUE TITLE
🐛 Bug: Textarea on Sidebar does not grow to fit contents

### ISSUE THREAD

**Issue by mnutt** [CopilotKit/CopilotKit#1628]
### ♻️ Reproduction Steps

1. Go to https://examples-coagents-ai-travel-app.vercel.app/
2. Type more than fits on one line.
3. The textarea does not automatically resize to fit the content like it does in the popup.

https://github.com/user-attachments/assets/45780323-89ef-4ad0-81ef-ea03a70a8a42

I was able to fix this with some custom css, though there may be more than needed here:
```css
  .copilotKitInputContainer {
    display: flex;
    flex-direction: column;
    flex-basis: fit-content;
  }

  .copilotKitInput {
    flex-basis: fit-content;
  }
  
  .copilotKitInput textarea {
    flex-basis: auto;
    flex-grow: 1;
  }
```

I reproduced this on my local app (1.8.4) and in the demo app, in Google Chrome 134 / Mac and Firefox 138 / Mac.

### ✅ Expected Behavior

As more text is added, the textarea height grows.

### ❌ Actual Behavior

Textarea stays the same size (one line high) and the content scrolls.

### 𝌚 CopilotKit Version

```shell
1.8.4
```

### 📄 Logs (Optional)

```shell

```
