### ISSUE TITLE
🐛 Bug: CopilotKit CSS conflicts with existing tailwind styles

### ISSUE THREAD

**Issue by dragos-cojocaru** [CopilotKit/CopilotKit#1857]
### ♻️ Reproduction Steps

1. Have `import '@copilotkit/react-ui/styles.css'` in a Next.js layout while you also have `import './globals.css'` in the same layout or parent layout
2. CopilotKit CSS will override (remove in my case) my existing styles, especially the dark theme styles

### ✅ Expected Behavior

`import '@copilotkit/react-ui/styles.css'` should not affected already existing styles.

I see this issue [was already reported before](https://github.com/CopilotKit/CopilotKit/issues/366), but no action was taken. Can you add a prefix to CopilotKit CSS as mentioned [here](https://github.com/CopilotKit/CopilotKit/issues/366#issuecomment-2137573263)?

### ❌ Actual Behavior

`import '@copilotkit/react-ui/styles.css'` affects already existing styles.

### 𝌚 CopilotKit Version

```shell
1.8.12
```

### 📄 Logs (Optional)

```shell

```

**Comment by orca-copilotkit** [comment]
@dragos-cojocaru This issue is on our radar. If you're experiencing production downtime and need urgent support, book a brief meeting at: https://cal.com/nathan-tarbert-copilotkit/15min

**Comment by tylerslaton** [comment]
Hi @dragos-cojocaru! 

Thank you for submitting the issue you're experiencing. We will be working on this soon and I'll keep you posted. In the mean time we're open to contributions for a fix from anyone in the community!

**Comment by dragos-cojocaru** [comment]
Hey @tylerslaton,
Do you have any update on this? We are currently waiting for this issue to be fixed :)

**Comment by ranst91** [comment]
Hey @dragos-cojocaru 

I am looking into this, but unfortunately I could not yet find where the issue is originating from.
To give you an understanding of the internals:
- We are not using custom tailwing classes. In fact, we are using regular tailwind classes with the intention of inheriting user styles. So for example, if we use `text-primary` and in your app you have set primary color to red, we expect the CPK text that uses it to turn red. When it comes to Tailwind, CopilotKit refrains, as a concept, from delivering opinionated styles.
- We do use custom styles, but for this we are utilizing simple css classes, in css files. e.g `.copilotKitInput`. [See here](https://github.com/CopilotKit/CopilotKit/tree/main/CopilotKit/packages/react-ui/src/css)
- The only Tailwind related "addition" we have, are prefixes css variables. [This is defined here](https://github.com/CopilotKit/CopilotKit/blob/main/CopilotKit/packages/react-ui/src/css/colors.css)

Can I ask you to try and dive into where the style overrides are coming from? Obviously I believe you that once importing CopilotKit css you are getting this, but I am trying to understand what is the unique situation that causes this. Would appreciate your cooperation

**Comment by PavanNimkar** [comment]
I’m interested in contributing and would like to work on this issue. Could @tylerslaton please assign it to me?

**Comment by tylerslaton** [comment]
Sure @PavanNimkar! We couldn't replicate this.

**Comment by PavanNimkar** [comment]
Thank you, @tylerslaton, for assigning the issue

**Comment by PavanNimkar** [comment]
@tylerslaton , can you clarify what you mean when you say 'we couldn't replicate this'?

**Comment by SukkaW** [comment]
We are also facing the same issue, after importing `import "@copilotkit/react-core/v2/styles.css";` our own CSS being polluted, result in our `hidden md:block` and `hidden:flex` not being effective:

<img width="790" height="404" alt="Image" src="https://github.com/user-attachments/assets/7073179d-86fd-4d36-aa6a-a6422df09ab0" />

It turns out that CopilotKit ships an already compiled tailwind css, **without any isolation**, and pollutes our own tailwind css.

**Comment by wj21067855** [comment]
import "@copilotkitnext/react/styles.css";

this is also conflict with @carbon/styles. :(

**Comment by IanVS** [comment]
My whole site turns to darkmode when I add `import "@copilotkit/react-core/v2/styles.css";`.  I can't figure out why so far.

**Comment by cctidal** [comment]
Also related #2920 
Pending PR https://github.com/CopilotKit/CopilotKit/pull/2660

This is what I do to workaround the issue https://github.com/CopilotKit/CopilotKit/issues/2920#issuecomment-3761205536

**Comment by tylerslaton** [comment]
Hey all, we're going to be tackling this this week. If anyone is interested in helping/testing, please feel free to reach out :)

**Comment by IanVS** [comment]
@tylerslaton we're in the middle of a migration to v2 components/styles, and would be happy to help test out any canary builds you might have.

**Comment by tylerslaton** [comment]
Great, will do! We're hoping to have one out this week. I'll keep you posted on that.

**Comment by ryanovas** [comment]
@ranst91 can you clarify this comment you made?

> We are not using custom tailwing classes. In fact, we are using regular tailwind classes with the intention of inheriting user styles. So for example, if we use text-primary and in your app you have set primary color to red, we expect the CPK text that uses it to turn red. When it comes to Tailwind, CopilotKit refrains, as a concept, from delivering opinionated styles.

As far as I can tell the v2 css completely overrides these variables:

```css
[data-copilotkit] {
  --background: oklch(100% 0 0);
  --foreground: oklch(14.5% 0 0);
  --card: oklch(100% 0 0);
  --card-foreground: oklch(14.5% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(14.5% 0 0);
  --primary: oklch(20.5% 0 0);
  --primary-foreground: oklch(98.5% 0 0);
  --secondary: oklch(97% 0 0);
  --secondary-foreground: oklch(20.5% 0 0);
  --muted: oklch(97% 0 0);
  --muted-foreground: oklch(55.6% 0 0);
  --accent: oklch(97% 0 0);
  --accent-foreground: oklch(20.5% 0 0);
  --destructive: oklch(57.7% .245 27.325);
  --destructive-foreground: oklch(57.7% .245 27.325);
  --border: oklch(92.2% 0 0);
  --input: oklch(92.2% 0 0);
  --ring: oklch(70.8% 0 0);
  --chart-1: oklch(64.6% .222 41.116);
  --chart-2: oklch(60% .118 184.704);
  --chart-3: oklch(39.8% .07 227.392);
  --chart-4: oklch(82.8% .189 84.429);
  --chart-5: oklch(76.9% .188 70.08);
  --radius: .625rem;
  --sidebar: oklch(98.5% 0 0);
  --sidebar-foreground: oklch(14.5% 0 0);
  --sidebar-primary: oklch(20.5% 0 0);
  --sidebar-primary-foreground: oklch(98.5% 0 0);
  --sidebar-accent: oklch(97% 0 0);
  --sidebar-accent-foreground: oklch(20.5% 0 0);
  --sidebar-border: oklch(92.2% 0 0);
  --sidebar-ring: oklch(70.8% 0 0);
}
.dark [data-copilotkit],[data-copilotkit].dark {
  --background: oklch(14.5% 0 0);
  --foreground: oklch(98.5% 0 0);
  --card: oklch(14.5% 0 0);
  --card-foreground: oklch(98.5% 0 0);
  --popover: oklch(14.5% 0 0);
  --popover-foreground: oklch(98.5% 0 0);
  --primary: oklch(98.5% 0 0);
  --primary-foreground: oklch(20.5% 0 0);
  --secondary: oklch(26.9% 0 0);
  --secondary-foreground: oklch(98.5% 0 0);
  --muted: oklch(26.9% 0 0);
  --muted-foreground: oklch(70.8% 0 0);
  --accent: oklch(26.9% 0 0);
  --accent-foreground: oklch(98.5% 0 0);
  --destructive: oklch(39.6% .141 25.723);
  --destructive-foreground: oklch(63.7% .237 25.331);
  --border: oklch(26.9% 0 0);
  --input: oklch(26.9% 0 0);
  --ring: oklch(55.6% 0 0);
  --chart-1: oklch(48.8% .243 264.376);
  --chart-2: oklch(69.6% .17 162.48);
  --chart-3: oklch(76.9% .188 70.08);
  --chart-4: oklch(62.7% .265 303.9);
  --chart-5: oklch(64.5% .246 16.439);
  --sidebar: oklch(20.5% 0 0);
  --sidebar-foreground: oklch(98.5% 0 0);
  --sidebar-primary: oklch(48.8% .243 264.376);
  --sidebar-primary-foreground: oklch(98.5% 0 0);
  --sidebar-accent: oklch(26.9% 0 0);
  --sidebar-accent-foreground: oklch(98.5% 0 0);
  --sidebar-border: oklch(26.9% 0 0);
  --sidebar-ring: oklch(43.9% 0 0);
}
```

There also seem to be some global typography styles that try to turn all my headers/body font into copilotkit styled versions I have to workaround.

Is there a reason this library is shipping with so much global code? Shouldn't the styles all be constrained to just the components from the lib? And allow for overriding the css vars so we can match colours?
